#! /usr/bin/python3
'''
这是一个解析ip子网掩码的python程序
'''

import os
import time
from IPy import IP
import re


def netwk(ipstr):
    needs = re.search('^(.*)\.(.*)', ipstr)
    res = re.search('^(.*)/(.*)', ipstr)
    ipaddress = res.group(1)
    segment = res.group(2)
    print('ip地址为： %s'% res.group(1))
    # print(res.group(2))
    if int(segment) >= 24:
        operandnk = re.search('^(.*)\..*', ipaddress).group(1) + '.0/' + segment
        operandnk_res = IP(operandnk).strNormal(2)
        network = re.search('^.*/(.*)', operandnk_res).group(1)
        print(network)

    elif 24 > int(segment) >= 16:
        operandnk = re.search('^(.*?)\.(.*?)\..*', ipaddress)
        # print(operandnk.group(2))
        operandnk_str = operandnk.group(1) + '.' + operandnk.group(2) + '.0.0/' + segment
        operandnk_res = IP(operandnk_str).strNormal(2)
        network = re.search('^.*/(.*)', operandnk_res).group(1)
        print('网关地址为：%s'% network)

    elif 16 > int(segment) >= 8:
        operandnk = re.search('^(.*?)\..*', ipaddress)
        # print(operandnk.group(2))
        operandnk_str = operandnk.group(1) + '.0.0.0/' + segment
        operandnk_res = IP(operandnk_str).strNormal(2)
        network = re.search('^.*/(.*)', operandnk_res).group(1)
        print(network)

    with open('/etc/network/interfaces', 'w') as f:
        f.write(
            "# interfaces(5) file used by ifup(8) and ifdown(8) \n"
            "auto lo \n"
            "iface lo inet loopback \n"
            "auto enp1s0 \n"
            "iface enp1s0 inet static \n"
            "address %s"% ipaddress + '\n'
            "netmask %s"% network + '\n'
            "gateway 192.168.20.1 \n"
            )

    with open('/etc/resolv.conf', 'w') as f:
        f.write(
            
            '# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8) \n'
            '# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN \n'
            'nameserver 127.0.0.1 \n'
            'nameserver 114.114.114.114 \n'
            )

if __name__ == '__main__':
    netwk(input('请输入ip/网段：'))
    #192.168.201.11/24
    os.system("ifconfig")
    os.system("/etc/init.d/networking stop")
    time.sleep(10)
    os.system("/etc/init.d/networking start")
    time.sleep(3)
    os.system("ifconfig")

            
            
