#!/usr/lib/python3

""" 
     这是一个配置网卡的脚本，有点搓，可以作为参考自己个写一个。需要安装 IPy 模块来解析网段生成子网掩码。在自己主机上运行时需要
     根据自己主机环境进行修改，例如：网卡名...
    
 """

import os
import time
from IPy import IP
import re


def network(ll):

    pat = re.compile(r"^(.*)/(.*)") 

    ipc = re.findall(pat,ll)
    ipp = ipc[0][0]

    bb = ipc[0][0]
    pcc = re.compile("^(.*)\.(.*)")
    dd = re.findall(pcc,bb)
    zw = dd[0][0] + '.0'+'/%s'%ipc[0][1]
    wg = dd[0][0] + '.1'
    ipc = IP(zw).strNormal(2)
    pat2 = re.compile(r"^.*/(.*)")
    cc2 = re.findall(pat2, ipc)
    zw = cc2[0]
    #写入DNS配置文件
    with open("/etc/resolv.conf",'w+') as dns:
        dns.write("#Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)" + "\n"
                  '#    DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN'+'\n'
                  "nameserver 127.0.1.1" + "\n"
                  "nameserver 114.114.114.114" + "\n")

    #写入 interfaces 文件
    with open("/etc/network/interfaces",'w+') as nk:
        nk.write("# interfaces(5) file used by ifup(8) and ifdown(8)"+'\n'
             "auto lo"+'\n'
             "iface lo inet loopback"+'\n'
             "auto enp8s0"+'\n'
             "iface enp8s0 inet static"+'\n'
             "address %s"%ipp +'\n'
             "netmask %s"%zw +'\n'
             "gateway %s"%wg +'\n'
             )
   # 配置 /etc/NetworkManager/NetworkManager.conf 后需要执行重启才生效
   # os.system('service network-manager restart')

    os.system('ifconfig')

    time.sleep(5)

    os.system('/etc/init.d/networking stop')

    time.sleep(10)

    os.system('/etc/init.d/networking start')
    
    time.sleep(5)

    os.system('ifconfig')

network(input('请输入ip/网段:'))
